"""new fields in user model

Revision ID: 086ba3f7c6c9
Revises: 728621073108
Create Date: 2019-10-30 20:43:25.016404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086ba3f7c6c9'
down_revision = '728621073108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
